<?php

use Illuminate\Database\Seeder;

class EmployeeProfileTableSeeder extends Seeder{

    public function run(){

        $data=[
        	[
                'creator_user_id'=>1,
                'employee_id'=>'0801 01',
                'name'=>'Md. Fazar A. Khan',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'1011 02',
                'name'=>'Florence Khan',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0617 119',
                'name'=>'Kabir Ahmed Khan',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0801 03',
                'name'=>'Md. Tanjil Khan',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0813 42',
                'name'=>'Md. Iftakhar Shaimul Hasan',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0417 117',
                'name'=>'Md. Shariful Islam',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0417 118',
                'name'=>'Asfak Uddin',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'1114 49',
                'name'=>'Md. Ershad Ali',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0810 08',
                'name'=>'Md. Abu Shaharia',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0612 32',
                'name'=>'Md. Mahabub Alam Howlader',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0616 79',
                'name'=>'Abu Sadat Bin Mokbul',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'1017 136',
                'name'=>'Md.Jasim Uddin Chowdhury',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'1116 97',
                'name'=>'Md. Shah Alam',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0516 74',
                'name'=>'Md. Samun Sarker',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0316 68',
                'name'=>'Farid Uddin Ahmed',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0717 122',
                'name'=>'Reasat Ud Daulah',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0211 07',
                'name'=>'Abdul Wahid Chowdhury',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0816 86',
                'name'=>'Shahriar Ahammed',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'1116 110',
                'name'=>'Shahadat Hossain',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'1214 50',
                'name'=>'Md. Sabbir Ali Khan',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'1117 137',
                'name'=>'Md. Mahabur Rahman',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0817 120',
                'name'=>'Mashfiqur Rahman Debu',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>null,
                'name'=>'Md. Rokon-Uz-Zaman',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>null,
                'name'=>'Md. Rumman Ahsan',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0517 121',
                'name'=>'Md. Abdur Razzaque',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0511 11',
                'name'=>'Md. Harun-Or-Rashid',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0612 34',
                'name'=>'Md. Afsar Uddin',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0112 25',
                'name'=>'Md. Sohel Rana',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'1013 44',
                'name'=>'Md.Nowsher Ali',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0411 16',
                'name'=>'Md. Sadikqul Islam',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0516 76',
                'name'=>'Mohammad Habibur Rahman',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0616 77',
                'name'=>'Md. Jobayer Hossan',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'1115 111',
                'name'=>'Md. Akram Hossen',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0115 112',
                'name'=>'Md. Abdul Momin',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0317 115',
                'name'=>'Md. Yousuf Ali',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0417 123',
                'name'=>'Md. Dulal Hossen',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'1117 139',
                'name'=>'Md. Abul Kalam',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'1117 140',
                'name'=>'Farid Maral',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>null,
                'name'=>'Md. Milon',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>null,
                'name'=>'Ali Hosen',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0411 14',
                'name'=>'Abdur Rahim',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'1215 63',
                'name'=>'Pran kumar Ray',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0815 71',
                'name'=>'Md. Abdul Jalil',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'1016 87',
                'name'=>'Md. Alamgir',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0117 116',
                'name'=>'Md. Siraj Mia',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'1017 135',
                'name'=>'Md. Abul Basar Garami',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0715 72',
                'name'=>'Md. Monir',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0917 141',
                'name'=>'Al Amin',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>null,
                'name'=>'Md. Yasin Ahmed',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>null,
                'name'=>'Md. Sumon',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],

            //popular-motors

            [
                'creator_user_id'=>1,
                'employee_id'=>'0117 103',
                'name'=>'Md. Mahamud Ullah',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0816 85',
                'name'=>'Md. Palash Uddin',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0816 84',
                'name'=>'Md. Al-Amin',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0115 53',
                'name'=>'Hasan Ali',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'1116 94',
                'name'=>'Md. Shafikul Islam',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'1216 101',
                'name'=>'Md. Roni Hasan',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0915 61',
                'name'=>'Md. Monir Hossen',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'1016 89',
                'name'=>'Jamir Uddin',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0617 125',
                'name'=>'Subel Barua',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'1017 133',
                'name'=>'Md. Maminul Islam',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0815 60',
                'name'=>'Md. Nymul Hasan Nazmul',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0417 128',
                'name'=>'Md. Arfatur Rahman',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'1116 91',
                'name'=>'Md. Pamruj Mia',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>null,
                'name'=>'Md. Masum Billah',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'1017 134',
                'name'=>'Md. Ahasan Kabir',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>null,
                'name'=>'Mohammad Sahidul Islam',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0717 132',
                'name'=>'Md. Jahirul Islam Shovo',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>null,
                'name'=>'Md. Nurul Islam',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>null,
                'name'=>'Md. Asad Khan',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0615 55',
                'name'=>'Md. Abdullah Asim',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0617 130',
                'name'=>'Saiful Islam',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0216 67',
                'name'=>'Md. Aminul Islam Mallik (Neamat)',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'1015 62',
                'name'=>'Onil Sharkar',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0117 107',
                'name'=>'Milton Kazi',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'0916 108',
                'name'=>'Dalim Hossen',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
            ],

        ];

        \DB::table('employee_profiles')->insert($data);

        $data=[
            [
                'employee_profile_id'=>1,
                'company_id'=>1,
                'department_id'=>1,
                'designation_id'=>1,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>2,
                'company_id'=>1,
                'department_id'=>1,
                'designation_id'=>2,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>3,
                'company_id'=>1,
                'department_id'=>2,
                'designation_id'=>3,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>4,
                'company_id'=>1,
                'department_id'=>2,
                'designation_id'=>4,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>5,
                'company_id'=>1,
                'department_id'=>2,
                'designation_id'=>5,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>6,
                'company_id'=>1,
                'department_id'=>2,
                'designation_id'=>5,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>7,
                'company_id'=>1,
                'department_id'=>2,
                'designation_id'=>6,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>8,
                'company_id'=>1,
                'department_id'=>3,
                'designation_id'=>7,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>9,
                'company_id'=>1,
                'department_id'=>3,
                'designation_id'=>8,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>10,
                'company_id'=>1,
                'department_id'=>3,
                'designation_id'=>8,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>11,
                'company_id'=>1,
                'department_id'=>3,
                'designation_id'=>8,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>12,
                'company_id'=>1,
                'department_id'=>3,
                'designation_id'=>8,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>13,
                'company_id'=>1,
                'department_id'=>3,
                'designation_id'=>9,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>14,
                'company_id'=>1,
                'department_id'=>3,
                'designation_id'=>10,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>15,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>11,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>16,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>11,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>17,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>12,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>18,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>13,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>19,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>13,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>20,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>13,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>21,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>10,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>22,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>13,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>23,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>14,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>24,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>15,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>25,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>16,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>26,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>17,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>27,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>17,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>28,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>18,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>29,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>19,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>30,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>18,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>31,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>18,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>31,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>18,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>32,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>18,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>33,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>20,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>34,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>20,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>35,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>20,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>36,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>20,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>37,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>20,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>38,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>20,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>39,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>20,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>40,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>20,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>41,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>21,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>42,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>21,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>43,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>21,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>44,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>21,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>45,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>21,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>46,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>21,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>47,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>21,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>48,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>22,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>49,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>22,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>50,
                'company_id'=>1,
                'department_id'=>4,
                'designation_id'=>23,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            //popular-motors
            [
                'employee_profile_id'=>51,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>10,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>52,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>9,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>53,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>9,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>54,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>10,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>55,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>9,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>56,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>9,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>57,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>10,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>58,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>10,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>59,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>10,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>60,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>10,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>61,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>10,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>62,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>10,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>63,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>10,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>64,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>10,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>65,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>10,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>66,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>10,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>67,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>10,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>68,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>10,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>69,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>10,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>70,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>10,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>71,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>10,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>72,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>24,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>73,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>18,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>74,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>18,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
            [
                'employee_profile_id'=>75,
                'company_id'=>2,
                'department_id'=>5,
                'designation_id'=>25,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
        ];

        \DB::table('employee_org_infos')->insert($data);

        $data=[
            [
                'creator_user_id'=>1,
                'employee_id'=>'EMP001',
                'name'=>'Libon Khan',
                'national_id'=>'123456789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'3',
                'present_address'=>'Lalbagh',
                'permanent_address'=>'Mirpur',
                'user_id'=>2
            ],
            [
                'creator_user_id'=>1,
                'employee_id'=>'EMP002',
                'name'=>'Alvi Taz',
                'national_id'=>'4654656789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'4',
                'present_address'=>'Azimpur',
                'permanent_address'=>'Lalbagh',
                'user_id'=>3
            ],[
                'creator_user_id'=>1,
                'employee_id'=>'EMP003',
                'name'=>'Factory Manager',
                'national_id'=>'4654656789',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'4',
                'present_address'=>'Azimpur',
                'permanent_address'=>'Lalbagh',
                'user_id'=>4
            ],[
                'creator_user_id'=>1,
                'employee_id'=>'EMP004',
                'name'=>'Own Driver',
                'national_id'=>'4654656790',
                'nationality'=>'Bangladeshi',
                'blood_group_id'=>'4',
                'present_address'=>'Motijheel',
                'permanent_address'=>'Bogura',
                'user_id'=>5
            ]
        ];

        \DB::table('employee_profiles')->insert($data);

        $data=[
            [
                'employee_profile_id'=>76,
                'company_id'=>1,
                'department_id'=>1,
                'designation_id'=>26,
                'working_unit_id'=>1,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],[
                'employee_profile_id'=>77,
                'department_id'=>1,
                'company_id'=>1,
                'designation_id'=>26,
                'working_unit_id'=>2,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],[
                'employee_profile_id'=>78,
                'department_id'=>1,
                'company_id'=>1,
                'designation_id'=>26,
                'working_unit_id'=>3,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],[
                'employee_profile_id'=>79,
                'department_id'=>1,
                'company_id'=>1,
                'designation_id'=>26,
                'working_unit_id'=>3,
                'employee_org_info_status_id'=>2,
                'employee_org_info_type_id'=>1,
            ],
        ];

        \DB::table('employee_org_infos')->insert($data);

    }
}
