<?php

use Illuminate\Database\Seeder;

class StocksTableSeeder extends Seeder{

    public function run(){
        $data=[
        	[
				'working_unit_id'=>1,
				'product_id'=>1,
				'product_status_id'=>1,
				'product_type_id'=>1,
				'inventory_receive_id'=>null,
				'receive_quantity'=>100,
				'inventory_issue_id'=>null,
				'issue_quantity'=>30,
				'allocated_quantity'=>0,
				'remarks'=>'Remarks',
				'creator_user_id'=>1,
				'updator_user_id'=>1,
        	],[
				'working_unit_id'=>1,
				'product_id'=>2,
				'product_status_id'=>1,
				'product_type_id'=>1,
				'inventory_receive_id'=>null,
				'receive_quantity'=>100,
				'inventory_issue_id'=>null,
				'issue_quantity'=>30,
				'allocated_quantity'=>0,
				'remarks'=>'Remarks',
				'creator_user_id'=>1,
				'updator_user_id'=>1,
        	],[
				'working_unit_id'=>2,
				'product_id'=>1,
				'product_status_id'=>1,
				'product_type_id'=>1,
				'inventory_receive_id'=>null,
				'receive_quantity'=>200,
				'inventory_issue_id'=>null,
				'issue_quantity'=>100,
				'allocated_quantity'=>0,
				'remarks'=>'Remarks',
				'creator_user_id'=>1,
				'updator_user_id'=>1,
        	],[
				'working_unit_id'=>2,
				'product_id'=>2,
				'product_status_id'=>1,
				'product_type_id'=>1,
				'inventory_receive_id'=>null,
				'receive_quantity'=>75,
				'inventory_issue_id'=>null,
				'issue_quantity'=>25,
				'allocated_quantity'=>0,
				'remarks'=>'Remarks',
				'creator_user_id'=>1,
				'updator_user_id'=>1,
        	],[
				'working_unit_id'=>3,
				'product_id'=>1,
				'product_status_id'=>1,
				'product_type_id'=>1,
				'inventory_receive_id'=>null,
				'receive_quantity'=>300,
				'inventory_issue_id'=>null,
				'issue_quantity'=>80,
				'allocated_quantity'=>0,
				'remarks'=>'Remarks',
				'creator_user_id'=>1,
				'updator_user_id'=>1,
        	],[
				'working_unit_id'=>3,
				'product_id'=>2,
				'product_status_id'=>1,
				'product_type_id'=>1,
				'inventory_receive_id'=>null,
				'receive_quantity'=>275,
				'inventory_issue_id'=>null,
				'issue_quantity'=>120,
				'allocated_quantity'=>0,
				'remarks'=>'Remarks',
				'creator_user_id'=>1,
				'updator_user_id'=>1,
        	]
        ];

        \DB::table('stocks')->insert($data);
    }

}
